Remove deprecated FileInfo.file and related code
hpoul/file_picker_writable pull request #18
Opened 2021-04-04 14:01 UTC by amake

As I mentioned at https://github.com/hpoul/file_picker_writable/issues/16#issuecomment-812502955 I would like to be able to use `FileInfo` to describe files that exist but that we haven't tried to read the contents of yet. Currently the requirement of a non-null `File` member in `FileInfo` prevents that.

2021-04-04 14:35 UTC, hpoul requested changes
thanks, looks good 👍️ just two small comments, maybe you can take a look.

2021-04-04 14:35 UTC, hpoul commented on lib/src/event_handling.dart
>      // ignore: deprecated_member_use_from_same_package
```suggestion
```

2021-04-04 14:35 UTC, hpoul commented on lib/src/event_handling.dart
>        // ignore: deprecated_member_use_from_same_package
```suggestion
```

2021-04-04 14:35 UTC, hpoul commented on lib/src/file_picker_writable.dart
> +    final file = File(result['path']!);
maybe we could extract this into a `_resultToFile(result)` method, so the `path` magic string is only in one place?

2021-04-04 20:45 UTC, amake commented on lib/src/file_picker_writable.dart
> +    final file = File(result['path']!);
Good idea, thanks. Done in https://github.com/hpoul/file_picker_writable/pull/18/commits/712ece541a2a0f4afc931f8bb1edcdebc6e5c070

2021-04-05 06:15 UTC, merged

2021-04-05 06:15 UTC, hpoul commented
Thanks 👍